/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAN_H_RPCGEN
#define _SCAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *String;

struct params {
	String dir;
	int min;
};
typedef struct params params;

struct response {
	int chars;
	int words;
	int rows;
};
typedef struct response response;

#define SCANPROG 0x20000013
#define SCANVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  response * file_scan_1(String *, CLIENT *);
extern  response * file_scan_1_svc(String *, struct svc_req *);
#define DIR_SCAN 2
extern  int * dir_scan_1(params *, CLIENT *);
extern  int * dir_scan_1_svc(params *, struct svc_req *);
extern int scanprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  response * file_scan_1();
extern  response * file_scan_1_svc();
#define DIR_SCAN 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int scanprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_String (XDR *, String*);
extern  bool_t xdr_params (XDR *, params*);
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_String ();
extern bool_t xdr_params ();
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAN_H_RPCGEN */
