/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "/home/studente/Desktop/Es8/scan.h"

bool_t
xdr_String (XDR *xdrs, String *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	 if (!xdr_String (xdrs, &objp->dir))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->chars))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->words))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rows))
		 return FALSE;
	return TRUE;
}
