/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "/home/studente/Desktop/Es9_Bench/votafattorex.h"

bool_t
xdr_String (XDR *xdrs, String *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_voto (XDR *xdrs, voto *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->operazione))
		 return FALSE;
	 if (!xdr_String (xdrs, &objp->candidato))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_classifica (XDR *xdrs, classifica *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->giudice, NUMGIUDICI,
			sizeof (String), (xdrproc_t) xdr_String))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( NUMGIUDICI ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->punti, NUMGIUDICI,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->punti;
					i < NUMGIUDICI; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->giudice, NUMGIUDICI,
			sizeof (String), (xdrproc_t) xdr_String))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( NUMGIUDICI ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->punti, NUMGIUDICI,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->punti;
					i < NUMGIUDICI; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->giudice, NUMGIUDICI,
		sizeof (String), (xdrproc_t) xdr_String))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->punti, NUMGIUDICI,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
